JuliaStats/MixedModels.jl

- src/linearmixedmodels.jl
- src/plsdiag.jl
- src/plsdiagWSMP.jl
- src/plsone.jl
- src/plstwo.jl
Replaced `contiguous_view` with `ContiguousView` in all source files where it hadn't been changed before (i.e. all but plstwo.jl).
> Updated deprecated 'contiguous_view' to 'ContiguousView'

- docs/api/MixedModels.md
- src/pls.jl
- src/remat.jl
- test/pls.jl
Merge branch for sorting the random-effects terms by number of levels.
> Origin orderterms

- src/MixedModels.jl
- src/bootstrap.jl
- src/cfactor.jl
- src/inflate.jl
- src/inject.jl
- src/linalg.jl
- src/logdet.jl
- src/paramlowertriangular.jl
Use `Compat.LinAlg.checksquare`.
> Fix for 0.5

- README.md
- REQUIRE
- docs/api/MixedModels.md
- docs/api/index.md
- src/GLMM/PIRLS.jl
- src/MixedModels.jl
- src/bootstrap.jl
- src/mixedmodel.jl
- src/pls.jl
The `glmm` function is not yet able to fit a model but things are far enough along to merge the branch.
The branch also contains several documentation updates.
> Merge the glmms branch

- docs/src/index.md
- docs/src/lib/internals.md
- docs/src/lib/public.md
- docs/src/man/fitting.md
- src/PIRLS.jl
- src/mixedmodel.jl
- src/pls.jl
See https://github.com/MichaelHatherly/Documenter.jl/pull/51 for details.
> Updates for Documenter.jl syntax changes

- src/PIRLS.jl
- src/mixedmodel.jl
- src/pls.jl
- src/remat.jl
- test/pls.jl
- test/scalarReTerm.jl
- test/vectorReTerm.jl
Also, add tests to get the proportion of source code lines covered over 80%
> Allow nAGQ=0 in fit! for GLMMs for much faster fits

- src/PIRLS.jl
- test/pirls.jl
Some documentation changes as well.
> Use named arguments in fit! method for the GeneralizedLinearMixedModel class

- src/modelterms.jl
This uses the correct row/column sparse matrix indices for vector ReTerms. (Fixes #86)
> fix method to convert FactorReTerm matrix to sparse matrix

- benchmark/REQUIRE
- benchmark/benchmarks.jl
- src/MixedModels.jl
- src/mixedmodel.jl
- src/modelterms.jl
- src/simulate.jl
- test/pls.jl
- Introduce benchmarks using the [`PkgBenchmark`](https://github.com/JuliaCI/PkgBenchmark.jl) package.
- add a `getΛ` extractor
> Pkg benchmark

- src/MixedModels.jl
- src/PIRLS.jl
- src/pls.jl
- src/types.jl
- test/pirls.jl
- test/pls.jl
> Fix dof  and nobs methods. Add tests

- src/linalg.jl
- src/modelterms.jl
Suggestions from @protogeezer for #116 and #117
> Fixes for #116 and #117

- .gitignore
- .travis.yml
- REQUIRE
- appveyor.yml
- benchmark/benchmarks.jl
- docs/jmd/GaussHermite.jmd
- docs/jmd/Representation.jmd
- docs/jmd/Simulations.jmd
- src/MixedModels.jl
- src/PIRLS.jl
- src/gausshermite.jl
- src/linalg.jl
- src/linalg/lambdaprods.jl
- src/linalg/logdet.jl
- src/linalg/rankUpdate.jl
- src/linalg/scaleInflate.jl
- src/mixedmodel.jl
- src/modelterms.jl
- src/pls.jl
- src/simulate.jl
- src/types.jl
- test/FactorReTerm.jl
- test/REQUIRE
- test/UniformBlockDiagonal.jl
- test/gausshermite.jl
- test/matrixterm.jl
- test/pirls.jl
- test/pls.jl
- test/runtests.jl
Updates for Julia v0.7.0  Need https://github.com/JuliaStats/StatsModels.jl/pull/72 to be merged to be able to pass tests on Julia v1.0.0
> 0.7updates

- src/gausshermite.jl
- src/types.jl
- test/pirls.jl
- test/pls.jl
- Use `getproperty` to query characteristics of the model and `setproperty` to install a new value of 'theta'.
> Getproperty

- src/modelterms.jl
Issue #145. Should be a bug fix from updating code to 0.7/1.0 and part of a patch release.
> Fix rank-deficient models

- test/pls.jl
Simple test for rank-deficient models
> Add test for rank deficient

- src/PIRLS.jl
- src/pls.jl
Allows same arguments constructors take to be passed through `fit`.
> Allow kwargs through fit

- src/pls.jl
- test/pls.jl
Fixes bug on `dof_residual` for `LinearMixedModel`
> Fixes bug on dof_residual for Linear

- docs/src/optimization.md
> Add missing ```math line in optimization docs

- .travis.yml
- Project.toml
- appveyor.yml
- docs/Project.toml
- docs/make.jl
- src/MixedModels.jl
- src/generalizedlinearmixedmodel.jl
- test/FactorReTerm.jl
- test/Project.toml
- test/UniformBlockDiagonal.jl
- test/pirls.jl
- test/pls.jl
- test/runtests.jl
Allows for `StatsBase.fit` method.
> Allow for `fit` to be used

- src/linalg.jl
- src/linalg/rankUpdate.jl
- src/linearmixedmodel.jl
- src/randomeffectsterm.jl
- src/remat.jl
- src/utilities.jl
- test/pls.jl
> Combine independent RE terms with same blocking variable

- src/remat.jl
- src/utilities.jl
- test/pls.jl
Closes #218
I haven't added a test yet.
> Switch to row-major ordering of correlations.

- Project.toml
Added the compat bounds for missing entries.
> Added the compat bounds for missing entries

- Artifacts.toml
- Project.toml
- README.md
- src/MixedModels.jl
- test/FactorReTerm.jl
- test/Project.toml
- test/UniformBlockDiagonal.jl
- test/fit.jl
- test/missing.jl
- test/pirls.jl
- test/pls.jl
- test/runtests.jl
Use a `TestData` artifact to download a tarball of feather files for the test data.
> Switch to Feather/Artifacts for test data

- src/linalg/rankUpdate.jl
- test/linalg.jl
A fall back for unusual data/model specifications.
> generic rankUpdate! method

- src/simulate.jl
> update docs, fix copy-paste error for parametricbootstrap methods

- src/generalizedlinearmixedmodel.jl
The title says it all. Just added a missing check for the GLMM show method.
> don't show unfitted GLMMs

- Project.toml
> Upgrade to version 1.0 of Tables

- test/pls.jl
Let's not get me started on how a given RNG's behavior can change for the same seed.
> change tests for simulate! and bootstrap for new Julia 1.5 RNG behavior 

- src/generalizedlinearmixedmodel.jl
- src/linearmixedmodel.jl
> change CoefTable column names to match GLM.jl

- src/generalizedlinearmixedmodel.jl
- test/pirls.jl
> ranef method for GLMM

- Artifacts.toml
`machines` data added to the `.tar.gz` file per @kliegl 's request.  Not sure I have followed the instructions in the comment correctly b/c I didn't really understand them.
> New version of data.tar.gz with machines dataset

- test/linalg.jl
> fix error check for differences in type aliases across Julia versions

- src/linearmixedmodel.jl
- test/pls.jl
Just knocking off a bunch of low-hanging fruit in terms of fixes/improvements that we can backport while finishing off 3.0....
This fixes #194 in the 2.x series.
> Backport reweighting bug fix

- Project.toml
- src/MixedModels.jl
- src/remat.jl
- Closes #366
- The dependency on `BlockDiagonals` was blocking updates on several other packages
> Remove dependency on BlockDiagonals

- docs/src/optimization.md
> describeblocks --> BlockDescription

- src/generalizedlinearmixedmodel.jl
> fix propogation of defaults in non-column table contructor

- docs/src/rankdeficiency.md
Hopefully this will return in a search result if users do a quick search before asking questions.
> PosDefException in rank deficiency docs

- src/generalizedlinearmixedmodel.jl
- src/linearmixedmodel.jl
- test/linalg.jl
- test/pirls.jl
- test/pls.jl
> GLMM refit!

- docs/src/GaussHermite.md
- docs/src/constructors.md
- docs/src/optimization.md
- docs/src/rankdeficiency.md
- src/generalizedlinearmixedmodel.jl
- src/linearmixedmodel.jl
- list `AIC`, `AICc`, and `BIC` in show output for both `LinearMixedModel` and `GeneralizedLinearMixedModel` #411
- clean up some phrasings in the documentation
> Clean up show methods and documentation

- benchmark/benchmarks.jl
- update the benchmarks to the current TestData contents
- should add benchmarks of GLMMs
- the `nested` example is still way off.  Somehow there must be compilation time in there.
- may need to allow more time per run if the longer benchmarks (`mrk17_exp1:[12]`, `ml1m:1`) are going to be useful.  These are only timed for 1 run at present.  Alternatively, just use some smaller, faster examples.
> Update benchmarks to TestData.

- .github/workflows/MKL.yml
- src/linalg/pivot.jl
- test/runtests.jl
I never get CI stuff to work the first time around, so very WIP.
Note that this only uses Julia 1.5 on Ubuntu 18.04 x86-64, but testing the full combinatorial explosion of MKL possibilities is just too much compute time/effort.
> CI using MKL

- Project.toml
> Add in Arrow 1.0 compatibility

- Project.toml
> Add back in the Arrow compat entry

- .github/workflows/TagBot.yml
Implements the changes recommended [here](https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249). 
This hasn't impacted us so far because we've been pretty active, but since TagBot uses the issue anyway, it won't hurt for us to update.
> Issue-based TagBot Trigger

- NEWS.md
- Project.toml
- docs/src/GaussHermite.md
I can change or omit the `DEV` modifier.
> Change version number to reflect breaking changes

- .github/workflows/Future.yml
- .github/workflows/Tier1.yml
- .github/workflows/documenter.yml
- Artifacts.toml
> Signed PooledArrays for 4.x

- src/linearmixedmodel.jl
> remove (unused) `named` kwarg from ranef

- src/likelihoodratiotest.jl
> use fname instead of term.sym directly

- NEWS.md
- src/generalizedlinearmixedmodel.jl
- src/likelihoodratiotest.jl
- test/Project.toml
- test/likelihoodratiotest.jl
- test/pirls.jl
> Add response family/distribution to GLMM type parameter

- NEWS.md
- src/mimeshow.jl
- test/mime.jl
These models are well defined so we should `show` them correctly.
> update mime show for RE without FE

- NEWS.md
I remembered by myself to update `NEWS.md` for this commit - just not before the actual commit.
> Update NEWS.md for #506

- docs/Project.toml
- docs/src/bootstrap.md
- src/bootstrap.jl
> Remove DataFramesMeta from the docs

- NEWS.md
- src/linearmixedmodel.jl
I'll immediately backport this to 3.7.1 if it looks fine.
cc @kliegl
> add support for BlockedSparse in `sparseL`

- NEWS.md
- src/linearmixedmodel.jl
- test/pls.jl
- at present this only works for a single grouping factor - the P.R. is mainly to show the outline
- needs tests, extension, much cleaning up
- and, of course, needs to be mentioned in NEWS.md
> Faster leverage function

- NEWS.md
@dmbates actually, while I've paused releasing 4.1, should we add a `ranef(model, fname)` method to complement the `condVar` method?
> NEWS update for 545

- Project.toml
- src/mixedmodel.jl
- test/bootstrap.jl
- test/modelcache.jl
- test/pirls.jl
- test/predict.jl
> issingular for GLMM with fast=false

- NEWS.md
- Project.toml
- src/mixedmodel.jl
- test/pirls.jl
- test/pls.jl
As previously discussed (since users can already just specify write `fit(MixedModel, ....)`
> constructor for MixedModel dispatches to subtype

- NEWS.md
The name should be the abstract data type, not the package name, shouldn't it?
> Correct a typo

- .github/workflows/documenter.yml
- README.md
- fix badge table 
- disable documenter builds on README changes
> fix README formatting

- src/generalizedlinearmixedmodel.jl
> Add a missing space

- benchmark/snoopspeed.sh
This just adds in the script I used to compare things for the precompilation improvements (https://github.com/JuliaStats/MixedModels.jl/pull/608#issuecomment-1115402204)
> add in benchmark script for precompile

- NEWS.md
- Project.toml
- src/linearmixedmodel.jl
- test/misc.jl
- test/runtests.jl
> better error msg for models without random effects

- issues/638/Manifest.toml
- issues/638/Project.toml
- issues/638/main.jl
I've added a for issue-level explorations. I didn't check in the data, but rather do a dynamic download. I figure this is good a way for us to see what we've been trying out and thinking as any other.
Of course, we need to be careful with de-identifying things if data are shared with us privately.
> exploration from issue 638

- .github/workflows/lts.yml
https://github.com/actions/runner-images/issues/5583
> Update Mac CI

- NEWS.md
- docs/src/optimization.md
- src/bootstrap.jl
- src/generalizedlinearmixedmodel.jl
- src/linearmixedmodel.jl
- src/predict.jl
- src/randomeffectsterm.jl
- src/simulate.jl
- test/bootstrap.jl
- test/pls.jl
closes #668
Did behavior change? Did you add need features? If so, please update NEWS.md **No**
> fix some typos

- README.md
> fix badge in README

- NEWS.md
- Project.toml
- src/bootstrap.jl
- src/profile/profile.jl
- test/Project.toml
- test/bootstrap.jl
- test/runtests.jl
> show method for bootstrap, profile; equal tail confint

- .github/workflows/benchmark.yml
- .github/workflows/current.yml
- .github/workflows/docs-cleanup.yml
- .github/workflows/documenter.yml
- .github/workflows/minimum.yml
- .github/workflows/nightly.yml
- .github/workflows/style.yml
originally started on this to see if it fixed the nightly CI problem, but then just decided to bump everything while I was at it.
> an assortment of CI bumps

- docs/Project.toml
No associated release necessary!
> bump Documenter compat

- NEWS.md
- Project.toml
- ext/MixedModelsPRIMAExt.jl
- src/MixedModels.jl
- src/prima.jl
- test/prima.jl
- test/runtests.jl
> experimental harness for PRIMA

- test/runtests.jl
until https://github.com/JuliaTesting/Aqua.jl/issues/343 is addressed
> stopgap fix for Aqua.jl on Julia 1.13 nightly
