REQUIRE, src/MixedModels.jl, src/pls.jl
These functions now have generic definitions in StatsBase.
Without this, a conflict arises when running the tests, so we can't tag a new release of StatsBase.
I didn't touch `npar`, but since it's exactly the same function as `df`, we should probably keep only one of them. I find `npar` slightly misleading since people won't usually think of sigma as a parameter, but maybe that's just me.
=> Use StatsBase 0.8.0's AIC, BIC and df

REQUIRE
instead of assuming they will be present from other dependencies
=> add Compat and DataArrays explicitly to REQUIRE

REQUIRE
To mirror https://github.com/JuliaLang/METADATA.jl/pull/6795/commits/11a02af019b6a709fde21823653b23527cd88776
(Hope you don't mind me using the new "allow edits by maintainers" feature to do that)
This is only technically necessary if there might be any future tags from this v0.4 branch,
but it doesn't hurt. If you're happy with things, no additional action is required from you
on the 0.5.8 tag.
=> change minimum StatsBase requirement to 0.11

src/PIRLS.jl, src/mixedmodel.jl, test/pls.jl
Fixing the bug in `ranef!` also affected `fitted` and `residuals`, which is why the tests changed.
=> Fix bug in ranef!, change isempty(offset₀) branch in setβθ!

src/PIRLS.jl, src/pls.jl, src/simulate.jl, test/pirls.jl
In the `fit!` method for `LinearMixedModel` objects, the parameters were initialized to `optsum.final`, not `optsum.initial`.   This doesn't really matter for a freshly created object because `final` is a copy of `initial`.  But it does play havoc with bootstrap replications and with simulations.
=> Fix bug introduced in last commit

src/pls.jl
The relative X tolerance criterion was previously set to optsum.ftol_rel
(this may have been a typo). This change changes it to optsum.xtol_rel
In addition, this sets the NLopt maxeval stopping criterion to
optsum.feval ( -1 by default)
=> Fix NLopt relative solution tolerance, add max feval NLopt criterion

src/mixedmodel.jl, src/pls.jl
The only thing the ModelFrame member of the LinearMixedModel type was used for was as an argument to `coefnames`.  I want to fix a mixed model without an actual model frame, so this PR replaces the ModelFrame member with a `Vector{String}` of fixed effect coef names which are then used directly.
=> replace model frame member with fixef coefnames

.travis.yml, REQUIRE, benchmark/REQUIRE, benchmark/benchmarks.jl, src/MixedModels.jl, src/PIRLS.jl, src/linalg.jl, src/linalg/cholUnblocked.jl, src/linalg/lambdaprods.jl, src/linalg/logdet.jl, src/linalg/rankUpdate.jl, src/linalg/scaleInflate.jl, src/mixedmodel.jl, src/modelterms.jl, src/pls.jl, src/simulate.jl, src/types.jl, test/FactorReTerm.jl, test/UniformBlockDiagonal.jl, test/pirls.jl, test/pls.jl, test/rankUpdate.jl, test/runtests.jl
- Switch to `BlockArray` types for the penalized least squares problem
- Distinguish between `ScalarFactorReTerm` and `VectorFactorReTerm`
- Use `UniformBlockDiagonal` type for diagonal blocks from `VectorFactorReTerm`
- More benchmarks
=> Block arrays

src/simulate.jl
Fixes #143 by manually converting the system `Int` to `LinearAlgebra.BlasInt` which may not be the same on some system BLAS (like arch linux).
=> convert info to BlasInt in Cholesky(::LowerTriangular)

src/newterms.jl, src/types.jl
I've moved all the logic for separating "matrix terms" (here fixed effects) and "non-matrix terms" (like random effects) into statsmodels in the latest commits.  Those also introduced a `MatrixTerm` that explicitly marks its children terms for concatenation at the `model_cols` stage (and guarantees that it produces a matrix) which also simplifies the code here somewhat
=> use MatrixTerm/is_matrix_term to separate fixed and ranef terms

src/generalizedlinearmixedmodel.jl, test/pirls.jl
Previously if you fit a GLMM with `nAGQ > 1` and later invoked the `deviance` method the value returned was that from the Laplace approximation (i.e. `nAGQ = 1`) not the actual deviance from the fit.  Add a method to provide for the correct result in these circumstances.
=> Use the recorded nAGQ in the deviance method if not given

docs/jmd/constructors.jmd, docs/src/constructors.md, src/MixedModels.jl, src/linearmixedmodel.jl, src/remat.jl, test/pls.jl
- add facilities to fit a model with vector-valued random effects in which estimation of the correlation parameters is suppressed.
=> Add the `zerocorr!` function, tests and documentation.

src/linearmixedmodel.jl, src/randomeffectsterm.jl, test/FactorReTerm.jl, test/missing.jl, test/runtests.jl
Because `StatsModels.ModelFrame` is never called directly, `StatsModels.missing_omit` is never invoked either.  If you extract the fixed effects as well as the blocking variables, then you can use that to create a `FormulaTerm` that `missing_omit()` understands and not lose any columns you need in the next step.
The extraction used here is rather kludgy at the moment.
=> Initial work on handling missing values

src/randomeffectsterm.jl, test/FactorReTerm.jl
As discussed in #123, this provides a more meaningful error message for non-categorical blocking variables, instead of e.g. implicitly treating numeric variables as weird categories (as in lme4). It also catches this during the parsing of the formula, which should give helpful error messages faster, compared to the old detection via missing contrasts during the construction of the random effects matrices.
=> Provide meaningful error messages for non-categorical blocking variables.

src/remat.jl, test/linalg.jl
This addresses the type ambiguity issue found in the my reworked example in #123:
```
ERROR: MethodError: lmulΛ!(::LinearAlgebra.Adjoint{Float64,ReMat{Float64,1}}, ::BlockedSparse{Float64,1,2}) is ambiguous. Candidates:
lmulΛ!(adjA::LinearAlgebra.Adjoint{T,#s32} where #s32<:ReMat{T,S}, B::BlockedSparse{T,S,P} where P where S) where {T, S} in MixedModels at /home/XXX/MixedModels.jl/src/remat.jl:125
lmulΛ!(adjA::LinearAlgebra.Adjoint{T,ReMat{T,1}}, B::M) where {T, M<:AbstractArray{T,2}} in MixedModels at /home/XXX/MixedModels.jl/src/remat.jl:116
Possible fix, define
lmulΛ!(::LinearAlgebra.Adjoint{T,ReMat{T,1}}, ::M<:(BlockedSparse{T,S,P} where P where S))
Stacktrace:
[1] updateL!(::LinearMixedModel{Float64}) at /home/XXX/MixedModels.jl/src/linearmixedmodel.jl:625
[2] #fit!#14(::Bool, …
```
=> another specialized lmulΛ! method.

.travis.yml, Project.toml
Increase minimum Julia version to 1.2 -- it's faster, it has several features we want, and the tests for 1.0 keep failing for no good reason (e.g. timeouts and failure to download `Coverage.jl`).
=> Drop support for Julia 1.0

src/MixedModels.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/remat.jl, src/varcorr.jl, test/pls.jl
- Switch to `NamedTuple` representation of standard deviations and correlations using the `m.σρs` extractor.
- `VarCorr` simply contains this `NamedTuple` and the dispersion parameter.
- Clean up the show method for `VarCorr`.
- Add tests for more coverage.
=> Restore printing of variance components

src/linearmixedmodel.jl
`parametricbootstrap` tries to write to elements of theta, but the theta that is
returned by getproperty is an SVector, so this errors
@palday I'll push a fix once the error is confirmed
=> Fix error from returning SVector for theta

docs/jmd/constructors.jmd, src/MixedModels.jl, src/randomeffectsterm.jl, test/pls.jl
This provides special syntax to be used within a formula to zero out
correlations on random effects terms:
``` julia
LinearMixedModel(@formula(Y ~ 1 + U + zerocorr(1+U|G)), dat)
```
which is equivalent to 
``` julia
zerocorr!(LinearMixedModel(@formula(Y ~ 1 + U + (1+U|G)), dat))
```
=> add zerocorr within formula

Project.toml, src/linearmixedmodel.jl, test/linalg.jl
Uses the suggestion from #216 to use `AbstractMatrix` as block type that doesn't lose subtype information to address `BlockArrays > 0.7.0` compatibility.
```julia
julia> B = Matrix{AbstractMatrix{Float64}}(undef,2,1)
julia> B[1,1] = fill(1.0,2,2)
julia> B[2,1] = sparse(I,2,2)
julia> A = mortar(B)
2×1-blocked 4×2 BlockArray{Float64,2,Array{AbstractArray{Float64,2},2},BlockArrays.BlockSizes{2,Tuple{Array{Int64,1},Array{Int64,1}}}}:
1.0  1.0
1.0  1.0
────────
1.0  0.0
0.0  1.0
julia> A[Block(1,1)]
2×2 Array{Float64,2}:
1.0  1.0
1.0  1.0
julia> A[Block(2,1)]
2×2 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
[1, 1]  =  1.0
[2, 2]  =  1.0
```
_Originally posted by @dlfivefifty in https://github.com/dmbates/MixedModels.jl/pull/216#issuecomment-542524324_
Resolves #215. Depends on #216 …
=> update BlockArrays support.

benchmark/benchmarks.jl, src/linalg.jl, src/remat.jl
Operations involving the potentially large matrix Λ involve stepping across blocks of columns (or rows) and applying a small triangular matrix,  λ.  By writing the inner operation as explicit loops instead of using views, a considerable amount of storage allocation can be avoided.
=> Replace multiplications, etc. with small matrices by explicit loops

src/simulate.jl, src/utilities.jl, test/pls.jl, test/utilities.jl
Introduce threading into `replicate`. 
Note that `replicate` now requires `f()` to be thread-safe. 
The naive version here seems to scale more or linearly with the number of threads up to the number of cores, but I'm still adding in locks to `simulate!` and `unscaledre!` to make them their RNG usage thread-safe. I've already added in thread-local storage so that they're not modifying the same model object.
=> threaded parametric bootstrap

src/linearmixedmodel.jl, src/remat.jl, test/pls.jl
Fixes pretty obvious typo and sets up tests to actually catch this.
While looking at the `zerocorr!` code for this, it became clear that we don't re-use the relevant portions of the final theta vector as starting values when modifying and re-fitting an existing model. Is this a desideratum?
=> make zerocorr!(mod) mark the model as unfitted

src/randomeffectsterm.jl, test/FactorReTerm.jl
The existing implementation of `g/x` syntax (estimates effects of `x` for each
level of grouping factor `g`) almost works for fixed effects as well.
The syntax `g/x` is equivalent to `g + fulldummy(g) & x`.
This PR adds tests for fixed effects and fixes a few oversights that only apply
in the fixed effects setting (e.g., use the `FullRank` schema to make sure that
`g` is promoted to full rank if necessary; promote `g` to full rank dummy coding
for the nested component).
Ultimately this should be moved into a separate regression formulae package.
=> fix up nesting (slash) syntax and add tests for fixefs too

src/linearmixedmodel.jl, test/pls.jl
This makes it easier to manipulate the `coeftable` for the fixed effects.
=> construct coeftable with hints for p-val and test-statistic cols

src/simulate.jl, test/pls.jl
This has two benefits:
1. Careless passing of literal ints still works (common new user mistake)
2. We control when conversion occurs.
3. More meaningful feedback (point of error) for invalid conversions / fail earlier.
=> convert incoming parameters in simulate! and parametric bootstrap

src/simulate.jl
Self-explanatory.  Means that the vector of samples returned by
`getproperty(::MixedModelBootstrap, :β)` is a vector of named tuples, aka a row
table and can be converted into any other table (e.g. a `DataFrame`) easily.
=> use a named tuple with coefnames for β in simulate

src/simulate.jl
Include `use_threads` in docstring and fix a copy-paste error for the implict RNG method.
=> update docs, fix copy-paste error for parametricbootstrap methods

src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/remat.jl, src/utilities.jl, test/pirls.jl, test/pls.jl
Questions:
@dmbates Note that this has been rebased onto current `#master`, which is why it's in my fork, but if you're mostly okay with the changes, I'll force push onto the main repo's `correlationPCA` branch.
=> new rePCA: now on correlations and with optional extra info

src/MixedModels.jl
People often look for help on `MixedModel`.  This adds a pointer to
`LinearMixedModel` and `GeneralizedLinearMixedModel` in the docstring.
=> add docstring for MixedModel supertype that points to concrete terms

src/remat.jl
I take the blame for this.
But note that the refit route will often give slightly different results (such is life with nonlinear optimization...):
```julia
using MixedModels
kb = fit(MixedModel, @formula(rt_raw ~ 1 + spkr * prec * load + (1 + spkr * prec * load | subj) + (1 + spkr * prec* load |item)), MixedModels.dataset("kb07"));
kbzc = fit(MixedModel, @formula(rt_raw ~ 1 + spkr * prec * load + (1 + spkr * prec * load | subj) + zerocorr(1 + spkr * prec* load |item)), MixedModels.dataset("kb07"));
kbzc_refit = fit!(zerocorr!(deepcopy(kb), [:item]));
```
```julia
julia> kbzc.optsum
Initial parameter vector: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0  …  0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Initial objective value:  30268.52732836507
Optimizer (from NLopt):   LN_BOBYQA …
```
=> fix value-preserving zerocorr!

src/utilities.jl
Calls to `MixedModels.dataset(nm)` now check for name `nm` in a Dict of cached datasets and skip the `Feather.read` step on the second and subsequent calls for the same `nm`.
=> Cache datasets

src/remat.jl
This makes it more convenient to work with correlation matrices from fitted
models.  I've added a doctest to show that it's equivalent to `VarrCor` at least
for one model fit to the KB07 data, but probably should have more extensive
tests.
=> add corrmat function that generates full correlation matrix of ReMat

src/femat.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, test/pls.jl
The docs should be updated to indicate that `coef` always refers to the full coefficient vector, as does `stderror` and `fixef` refers to the truncated coefficient vector.  Furthermore this extends to associated functions like `coefnames` and `fixefnames`.  However, I think it is better to do this in the version from #283
=> Add stderror! method, distinguish coef and fixef

src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, test/fit.jl
This adds/fixes methods for  `GLM.dispersion` and `StatsBase.dof_residual` for `GeneralizedLinearMixedModel` (closes #248 and potentially #206).
Questions from late-night coding confusion:
Here some samples that make me doubt myself.
```julia
julia> using MixedModels, RCall
julia> glmm = GeneralizedLinearMixedModel(@formula(yield ~ 1 + (1|batch)), MixedModels.dataset(:dyestuff),Normal(),SqrtLink())
Generalized Linear Mixed Model fit by maximum likelihood (nAGQ = 1)
yield ~ 1 + (1 | batch)
Distribution: Normal{Float64}
Link: SqrtLink()
Deviance: 115249.4629
Variance components:
Column    Variance  Std.Dev. 
batch    (Intercept)  1961.0615 44.283874
Residual              4266.2037 65.316183
Number of obs: 30; levels of grouping factors: 6
Fixed-effects parameters: …
```
=> GLMM dispersion and dof_residual

test/statschol.jl
The tests for the Cholesky decomposition and pivot don't actually require us to meet any distributional assumptions, so I replaced the draws from the RNG with simple ranges.
=> remove RNG from cholesky test

Project.toml
Change the development version to unambiguously indicate that it's not part of the 2.x series (especially since we've now released 2.3).
=> Change development version

.github/workflows/Future.yml, Artifacts.toml, src/arraytypes.jl, src/linalg.jl, src/linalg/cholUnblocked.jl, src/linalg/rankUpdate.jl, src/remat.jl, test/UniformBlockDiagonal.jl, test/pls.jl
- replace and remove code to by-pass creation of views in some linear algebra operations, especially those related to `UniformBlockDiagonal` arrays and some pre- and post-multiplications by a repeated block diagonal array.
- prior to Julia v1.5.0 expressing these operations using views required a lot of allocations and garbage collection.  v1.5.0 does away with these allocations.  Many thanks to those who made this happen.
=> restore the use of views not @simd workarounds

src/arraytypes.jl, test/pirls.jl
- Don't reuse the `fms` name for formulas in the tests.
- Avoid code duplication in copying a `UniformBlockDiagonal` to `Matrix`
=> Clean up parts of code and tests

src/femat.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, test/pls.jl
The `parmap` field in a `LinearMixedModel` is a vector of triples of the form `(term, row, column)` giving the mapping from the elements of the θ parameter vector to the positions in the λ matrices for each random-effects term.  Storing this as a separate field allows for cleaner logic in methods for `nθ`, `setθ!`, and `getθ!`.
=> Add and use parmap field.

src/linearmixedmodel.jl, test/pls.jl
Closes #194.
The fundamental problem was that the weights weren't taken into account when creating A and L. Since the weights never changed, `reweight!` was also never called, which would have updated them accordingly.
=> use weights when fitting LMM

src/randomeffectsterm.jl, test/pls.jl
After #269, a formula like `(1|x) + (y|x)` produces an error because we're
trying to add an extra intercept term to `(y|x)`, producing a non-unique
`(Intercept)` term.  This PR checks whether the schema associated with `|x` has
already seen or generated an intercept term in any earlier term before adding
one.  With this change, `(1|x) + (y|x)` is equivalent to `(1|x) + (0+y|x)`.  I
have a really hard time seeing why someone would want the behavior in those
cases to be different but maybe I just haven't thought about it hard enough
Inspired by @palday's comment in #255.
=> make (1|x) + (y|x) equivalent to (1|x) + (0+y|x)

src/arraytypes.jl, src/linalg/rankUpdate.jl, src/linearmixedmodel.jl, src/remat.jl, test/UniformBlockDiagonal.jl, test/linalg.jl
Clean up `rankUpdate!` methods.  In particular use Hermitian{T, Diagonal{T, Vector{T}}} instead of branching on the diagonal case in `updateL!`.  We want to use method dispatch instead of `if` statements that I had in the code.  This should be rebased on master after #329 is merged.
Closes #290.
=> Rank update

README.md
Closes #342
- Fix link for T1 and T2 shields
- Added the alt text to the shields
- Updated the docs dev shields from latest (deprecated name)
For reference: the syntax used for the shields is
```
[![alt text][image]][hyperlink]
```
=> Fix incorrect link on T1-T2 shields

src/linalg/rankUpdate.jl, src/linearmixedmodel.jl
- For Julia v1.5.0 and later it is an advantage to use views, as in this `rankUpdate` method for sparse `A`
- Slightly cleaner code for `ssqdenom`.  If I am reading the profile timings correctly, `ssqdenom` is a non-negligible part of the time spent in `objective`.
=> Use views, clean up ssqdenom

src/linearmixedmodel.jl
Keeping the same behavior, just updating the doc string.
=> change ranef doc string to match default args

.github/workflows/Future.yml, src/linearmixedmodel.jl, src/remat.jl, test/FactorReTerm.jl
There was a bug in how random effects like `(1 | a&b)` worked with amalgamate
and `fnames` (and hence `VarCorr` and display), because those paths were still
trying to use the `.sym` field on the grouping term.  I've replaced all
instances where `.sym` is used on a grouping term with a call to `fname`
(introduced in #197).
Also adds tests for `fit` with nesting and `&` in random effect grouping to
check the whole pipeline and to test equivalency of `(1 | a/b)` and `(1 | a&b) +
(1 | a)` (using the pastes data).
=> Fix grouping name and amalgamate for interaction grouping terms

src/linalg/statschol.jl
This fixes one tiny facet of the bigger issue lurking in #324.
In particular, OpenBLAS on SkyLakeX can do something weird for some (full rank!) matrices:
- The pivoted Cholesky estimates rank below full.
- The unpivoted Cholesky has `info ==0`, which means that the unpivoted Cholesky succeeded, suggesting numerical full rank.
In this case, the old code generated an invalid permutation consisting of the identity permutation with an extra element `0` appended to the end. The fix here trusts the success of the unpivoted Cholesky more than the rank of the pivoted Cholesky.
=> Fix for one tiny aspect of the rank deficiency issues

.github/workflows/Tier1.yml, src/likelihoodratiotest.jl, src/utilities.jl, test/likelihoodratiotest.jl, test/utilities.jl
For now, we're keeping `likelihoodratiotest` in. Two main reasons for that:
1. We print the formulae (but this can change)
2. We use don't check nesting (just basic compatibility in terms of family, links, objective, etc.). This means we get fewer false positives in cases like alternative specifications of compound symmetric random effects.
Closes #320.
=> StatsModels.lrtest support methods

src/remat.jl, src/utilities.jl, test/utilities.jl
Closes #340.
Sample of output:
```julia
julia> m1 = fit(MixedModel, @formula(score ~ 1 + Machine + (1 + Machine | Worker)), MixedModels.dataset(:machines))
Linear mixed model fit by maximum likelihood
score ~ 1 + Machine + (1 + Machine | Worker)
logLik   -2 logLik     AIC        BIC    
-108.2089   216.4178   236.4178   256.3077
Variance components:
Column    Variance Std.Dev.   Corr.
Worker   (Intercept)  13.813236 3.716616
Machine: B   28.684049 5.355749 +0.49
Machine: C   11.240468 3.352681 -0.36 +0.30
Residual               0.924687 0.961606
Number of obs: 54; levels of grouping factors: 6
Fixed-effects parameters:
──────────────────────────────────────────────────
Coef.  Std. Error      z  Pr(>|z|)
──────────────────────────────────────────────────
(Intercept)  52.3556      1.53414 …
```
=> PCA row labels

Project.toml, docs/Project.toml, docs/src/constructors.md, src/randomeffectsterm.jl
- closes #255 
- add a docstring for `fulldummy` and an example in the `constructors.md` source file for the online documentation
=> Documentation for fulldummy

src/bootstrap.jl
For now, I would like to leave the threading option in the API for a few reasons:
1. There are some machines with dozens (or even > 100 cores) where there might actually be some boost from threading at both the BLAS and simultaneous fits levels. These aren't so rare in university clusters -- I have seen a few in neuroscience.
2. I suspect it might be possible to eek out a bit more of a performance boost with finer grained locking, but that's not for today.3
3. If someone is using an alternative BLAS that isn't multi-threaded but still has multiple cores (maybe this is the case on ARM?), then they can still get a boost from multithreading.
=> note on threading in bootstrap

src/generalizedlinearmixedmodel.jl
This is a nasty, subtle bug about where you set the defaults.
=> fix propogation of defaults in non-column table contructor

Artifacts.toml, src/utilities.jl, test/modelcache.jl
- Change in `show` method for `PCA` to avoid `string.` applied to a `LowerTriangular` matrix
- "Prime the pump" by starting the `fittedmodels` Dict with a value.  1.6.0-DEV seems to hang on compilation for any call to `models` without that.
- Update a comment in `Artifacts.toml`
- Fixes #387, fixes #402
=> Fixes for running tests on 1.6.0-dev

Artifacts.toml, src/linearmixedmodel.jl, test/FactorReTerm.jl, test/likelihoodratiotest.jl, test/modelcache.jl, test/pirls.jl, test/pls.jl
- use version 4 of `arrow.tar.gz` from https://osf.io
- drop columns that can be computed on the fly; specifically `pastes.sample` and `contra.urbdist`
- adjust tests to use the modified data sets
- undo changes to cached fitted models in `test/pls.jl` 
- remove dependency of `test/pls.jl` on `DataFrames` package
=> update TestData in Artifact

.github/workflows/Tier1.yml
I think this is what Documenter needs in order to deploy documentation for tagged versions properly. Will hopefully fix stable docs issues.
=> Run CI on tag push, not on release creation

Project.toml, src/generalizedlinearmixedmodel.jl, src/likelihoodratiotest.jl, src/linearmixedmodel.jl, src/utilities.jl
The ambiguity is between `propertynames(::Any, ::Bool)` and the overloads in this package `propertynames(::T, ::Any)` for various types `T`. Since the second argument should always be a `Bool` anyway, we can simply add the type annotation to the function signature to fix the ambiguity.
=> Fix `propertynames` method ambiguity on Julia nightly

NEWS.md, Project.toml, docs/src/bootstrap.md, src/bootstrap.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/mixedmodel.jl, src/simulate.jl, test/bootstrap.jl, test/modelcache.jl, test/pirls.jl, test/utilities.jl
Closes #245.
I had to add in a few accessor-to-preallocated-buffer methods for GLMM elsewhere (`fixef!`, etc.). 
~`stderror!` actually does a hidden allocation, but I'll fix that as soon as I've looked up `StatsBase.stderror`.~
~There's also still some debugging code in there, but it should otherwise be in a good state to check for conceptual errors.~
```
julia> using DataFrames
julia> using MixedModels
julia> using StableRNGs
julia> contra = MixedModels.dataset(:contra)
Arrow.Table: (dist = ["D01", "D01", "D01", "D01", "D01", "D01", "D01", "D01", "D01", "D01"  …  "D61", "D61", "D61", "D61", "D61", "D61", "D61", "D61", "D61", "D61"], urban = ["Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y"  …  "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"], livch = ["3+", "0", "2", "3+", "0", "0", …
```
=> simulate! and thus parametricbootstrap for GLMM

src/generalizedlinearmixedmodel.jl, test/runtests.jl, test/utilities.jl
- Tests were failing under MKL because `openblas_get_config()` is not defined.
- Rephrase a warning message
- Move definition of `io` inside a `testset` in `test/utilities.jl` to avoid later warning on redefinition in `test/pls.jl`.
=> Check BLAS vendor, fix test warning, rephrase warn

test/utilities.jl
There is a very weird race condition that seems to arise in Julia 1.5 and which I can't consistently replicate.  I'm pretty sure the locking is correct. I suspect it's actually a floating point issue interacting in a fun way with threading. If it were only Julia threads there, then you would have the exact same floating point operations for each iteration, but the iterations potentially out of order (hence the sorting). But I think some of layers of optimization are breaking that assumption and that test should be made approximate but with a tight tolerance.
=> loosen floating point equality constraint

src/linalg.jl
Should fix the failure on nightly.
=> Swap adjoint and triangular wrappers

src/linalg/pivot.jl, test/runtests.jl
When using [`MKL`](https://github.com/JuliaComputing/MKL.jl) on a 64-bit Ubuntu system I found that I needed to set
```
ENV["USE_BLAS64"]=true
```
before building `MKL` or there would be a missing method error in the call to `QRPivoted`.  I believe that, by default, MKL uses 32-bit integers but OpenBLAS uses 64-bit integers.  The `piv` vector was being constructed as `collect(1:n)` hence it would default to 64-bit integers.
I think it is because the second external constructor for `QRPivoted` in the `LinearAlgebra` package
```
function QRPivoted{T}(factors::AbstractMatrix, τ::AbstractVector, jpvt::AbstractVector) where {T}
QRPivoted(convert(AbstractMatrix{T}, factors),
convert(Vector{T}, τ),
convert(Vector{BlasInt}, jpvt))
end
```
which would change the eltype of `jpvt` isn't being called …
=> Force BlasInt type for piv

test/pirls.jl
Drop the call to `categorical!` in `test/pirls.jl`.  Also clean up the example a bit using `PooledArray` instead of a `CategoricalArray`.
=> categorical! no longer in DataFrames 0.22

Artifacts.toml, src/MixedModels.jl
It seems challenging to have lazy artifact downloading be compatible with Julia < 1.6 and 1.6+, see recent test failures and [Discourse](https://discourse.julialang.org/t/recommended-transition-to-lazyartifacts/). However, we use the `TestData` artifact in `__init__` so they're downloaded with the very first `using MixedModels`, which we can assume most users will want to do not too much after `]add MixedModels`. So we can avoid all the laziness issues and just be eager. Slightly longer download times upon initial install, but since the artifacts system has its own caching, there shouldn't be any real performance issues as long as we don't change `TestData` too often.
=> Eagerness to avoid LazyArtifacts 

Artifacts.toml, Project.toml, src/linalg/rankUpdate.jl, test/modelcache.jl, test/pls.jl
Add optimized rank update for Diagonal L with dense A.
Note that we "found" this optimization via a missing method for a complicated nested type in `LinearAlgebra`.
Closes #445.
=> rankUpdate! method for Diagonal + Dense

NEWS.md, Project.toml, src/linalg/rankUpdate.jl, test/modelcache.jl, test/pls.jl
=> rankUpdate for BlockDiagonal by Dense

.github/workflows/TagBot.yml
This is just a copy-paste job of the default TagBot template with an added link for the NEWS file.
=> Automatically link to NEWS file in release notes

Project.toml, src/MixedModels.jl, src/blockdescription.jl, src/generalizedlinearmixedmodel.jl, src/linalg/logdet.jl, src/linearmixedmodel.jl, src/utilities.jl, test/Project.toml, test/pls.jl
- `BlockArray`s were only being used to store and access different matrices that formed the blocks of the `A` and `L` components of a `LinearMixedModel` object.
- Replace the `BlockArray`s with  `Vector{AbstractMatrix{T}}` and functions to convert an `[i,j]` index in the lower triangle to an index into the vector
- Within the vector, the blocks in the lower triangle are stored in _row-major_ order because this simplifies the conversion of row-column to linear index
- Because this change will require a new major release number will consider also changing to a single `Xy` block instead of separate blocks.  Nothing in the update of the Cholesky factor requires separate handling of the blocks associated with `X` and with `y`.
=> Use vector of matrices for A and L in LinearMixedModel

NEWS.md, docs/src/constructors.md, src/randomeffectsterm.jl, test/FactorReTerm.jl
This fixes #462 and more or less follows the plan outlined there: it adds a
method for `Base.:|` for two terms which returns a `RandomEffectsTerm`, and adds
an additional layer of indirection for `apply_schema` to operate on the
"untyped" `RandomEffectsTerm`s created by that process.  I've also made the
analogous changes to `zerocorr` (although that runtime method was actually
already in place, it didn't, you know, work...)
To my mind, the one big wart here is that we're "claiming"
`Base.:|(::TermOrTerms, ::TermOrTerms)` which wouldn't play nicely with another
package that also wants to provide a different set of semantics for `|` (at
run-time).  I first thought that we could do the same trick that
FilePathsBase.jl does with `/` (creating a new `/` function that falls back to
`Base./` for …
=> Runtime random effect terms (and zerocorr)

NEWS.md, Project.toml, src/MixedModels.jl, src/blockdescription.jl, src/generalizedlinearmixedmodel.jl, src/likelihoodratiotest.jl, src/linearmixedmodel.jl, src/mdshow.jl, src/mixedmodel.jl, src/optsummary.jl, src/randomeffectsterm.jl, src/varcorr.jl, test/markdown.jl, test/runtests.jl
=> BACKPORT:  Markdown show methods for our types 

.github/workflows/MKL.yml, NEWS.md, src/Xymat.jl, src/linalg/pivot.jl, test/pivot.jl
- add `statsrank` to compute the rank and pivot vector for a model matrix using a pivoted QR decomposition
- modify tests, etc.
- remove `statsqr` and `statscholesky` functions
=> QR-Based Rank Determination and Pivoting

.github/workflows/TagBot.yml, NEWS.md, Project.toml, docs/src/bootstrap.md, src/bootstrap.jl, test/bootstrap.jl
Doing this is as a 3.x release, but I'll of course port this into the development version. I think it's useful enough for an immediate release.
This also contains a few other fixes:
- the doc fix from #483 
- the TagBot release notes now strongly suggest that users look at NEWS rather than the closed issues/PRs because those can include changes to other parallel development streams.
=> shortestcovint for MixedModelBootstrap objects

.github/workflows/TagBot.yml, NEWS.md, docs/src/bootstrap.md, src/bootstrap.jl, test/bootstrap.jl
This brings #484 to the 4.0-DEV series.
I have also updated the NEWS file for the Xy block changes.
=> FORWARDPORT: shortestcovint for MixedModelBootstrap objects

.github/workflows/Future.yml, NEWS.md, src/pca.jl, src/remat.jl, src/utilities.jl, test/pls.jl
Closes #487 .
I had to loosen some type constraints in various places to make this work and I didn't add in any additional `mul!`  methods, so I don't know if we're fully taking advantages of this. @dmbates Feel free to add those in if you want, but those wouldn't be breaking changes.
I also changed `rownormalize!` to be non mutating. This made specializing for `Diagonal` easier and actually cut out an extra allocation.
=> Diagonalize ZeroCorr

.github/workflows/Tier1.yml, .github/workflows/documenter.yml, README.md
I've removed 1.5 from the tests because we're already doing a lot of testing and if things work on 1.4 and 1.6, they probably work on 1.5. 
As soon as 1.6 is officially declared LTS and 1.7 is released, then we can test on `[1.6, 1]` for Tier 1 and `[1.4]` for Tier 2 (or whatever the last version of Julia with all the linear algebra features we need is).
=> update standard tests to include 1.6

NEWS.md, Project.toml, src/linearmixedmodel.jl
=> Deprecate `named` kwarg in 3.x branch

NEWS.md, Project.toml, src/MixedModels.jl, src/generalizedlinearmixedmodel.jl, src/likelihoodratiotest.jl, test/likelihoodratiotest.jl
=> BACKPORT: LRT  for comparing non-mixed to mixed models 

src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/predict.jl, src/remat.jl, src/simulate.jl
- `unscaledre!` had methods that didn't really correspond to simulating and incorporating unscaled random effects.  
- These methods are rewritten here as `LinearAlgebra.mul!` methods.
=> LinearAlgebra.mul! instead of unscaledre!

test/matrixterm.jl
I kept forgetting the reason that one of our tests is still broken and eventually decided to add a comment to remind myself.
=> Add explanation for a broken test.  Correct a typo

src/remat.jl, test/pls.jl
- Add internal methods for σs for `ReMat{T,S}` so the case of a Diagonal λ is handled properly
- Add a test
- Closes #531
=> σs for Diagonal ReMat and test

NEWS.md, src/likelihoodratiotest.jl, src/utilities.jl, test/utilities.jl
- rename `allequal` to `isconstant`
- extend the base method to handle empty collections and iterators that include missing values
- add tests
=> Rename allequal to isconstant

NEWS.md, Project.toml, docs/src/optimization.md, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/optsummary.jl, test/pirls.jl, test/pls.jl
~Addresses (but does not close) #549 (because we want to change `OptSummary` later to be smarter about this).~
Closes #549. There is a minor inefficiency in that `initial`, `final`, `finitial`, `fmin` store information duplicated in the `fitlog`. Not duplicating this information (by cheating and using properties that redirect to the relevant field entries) turns out to make the bookkeeping a lot messier, so I've let this inefficiency remain (which also keeps better compatibility). I use `Vector` inside of the log instead of `SVector` because the changing size of the parameter vector in GLMM creates problems. 
It also seems that I might have found another case where julialang/julia#40048 isn't as fixed as we had hoped -- I get a big stackoverflow type inference dump as a Heisenbug when …
=> add `fitlog`

src/linearmixedmodel.jl, test/pls.jl
- `sparseL` gains an optional `fname` argument.  When a grouping factor name is given for this argument the return value consists of the lower-right triangle starting at that the rows and columns for that factor.
- `condVar` gains a method with a second argument `fname`.  When given the conditional variance array for that factor only is returned.
- the default `condVar` now just iterates over the grouping factor names.  ~(The old code is retained for comparison but will never be executed - it should be removed after review of this PR.)~
- the main use of `condVar` is in `MixedModelsMakie.caterpillar` which can now be simplified somewhat.
- this should provide considerable time savings for models like those fit by @kliegl to the FFGK21 dataset when only the caterpillar plot for the Schools …
=> Added opt. fname argument to sparseL and condVar

NEWS.md, Project.toml, src/bootstrap.jl, test/bootstrap.jl
- expand the type definition for the original fit (which I view as bugfix-esque, so patch)
- added a `Base.length` method (technically new functionality so minor release)
Closes #560
=> Support for  zerocorr in the bootstrap

NEWS.md, Project.toml, src/MixedModels.jl, src/bootstrap.jl, src/linearmixedmodel.jl, src/serialization.jl, test/bootstrap.jl
~more just organizing my thoughts than any real effort~
Moved some serialization things over to their own file and gave us a TODO list. For now, I would recommend that users use JLD2 to store their bootstrap results and then constrain their JLD2 and MixedModels major version.
=> option for reduced precision in bootstrap results

NEWS.md, Project.toml, docs/src/prediction.md, src/bootstrap.jl, src/predict.jl, test/bootstrap.jl
Closes #569 
There seems to be a new issue in the docs when `predict` is called on a model with a function term (e.g. division) in the response. For now, I've just made a work-around.
=> Fix allpars for zerocorr

Project.toml, src/generalizedlinearmixedmodel.jl, test/pirls.jl
Benchmarking suggests that the GLM inits we're currently using are the best for small models (although at a few hundred millisecond total difference in the fit, it's realistically a wash). But things get more interesting if we look at big models.
Here's an example from the English Lexicon project data -- I've split it into two plots because the scale changes pretty dramatically.
**First 50 iterations (after LMM fitting when the LMM is used)**  
**All successive iterations**
Here's the dataframe showing the progress (wrapped in a zip file to make GitHub happy):
[glmm_fitlog_by_init.arrow.zip](https://github.com/JuliaStats/MixedModels.jl/files/7805404/glmm_fitlog_by_init.arrow.zip)
The relevant timing info
```julia
Minimizing 973   Time: 1:42:50 ( 6.34  s/it) # GLM init
6179.284576 seconds …
```
=> Allow LMM to init GLMM

NEWS.md, Project.toml, src/bootstrap.jl
I broadened the type restriction so that some of the stuff I'm working on in MixedModelsPermutations can use `shortestcovint` without adding needing a new method definition for `MixedModelPermutation`. 
=> broaden shortestcovint to fit collection

NEWS.md, Project.toml, docs/src/prediction.md, src/predict.jl
No behavioral changes, but we updated a docstring enough that a patch release might be worthwhile.
@kliegl is the new explanation clearer?
=> rework `predict` docstring

NEWS.md, Project.toml, src/predict.jl
There are a couple of improvements here:
- using `sortperm` directly instead of faking it with `sort(::Range)`
- views
- skip actually computing the BLUPs for the hidden new model. They're nonsensical, the computation can fail because the new model hasn't actually been fit, and they'll be overwritten by the relevant entries from the old model.
There will be a merge conflict with #603 for NEWS.md, but I'll sort that out after the first of this is merged.
=> Efficiency improvements in `predict`

NEWS.md, Project.toml, src/linearmixedmodel.jl, test/pls.jl
Closes #611
This should help address some problematic models. The basic idea is to rescale the initial identity scaling by dividing by a large number, where "large" is the product of the largest weight by the largest response value. In other words, for poorly constrained problems, we change the initial guess to already have a good amount of shrinkage and see if that helps.
I tried more naive ways of rescaling the weights or even standardizing all variables in the model, but that didn't help. @dmbates if you're happy with this solution, I can add tests and updatee NEWs, etc., but I have rather mixed feelings about it myself.
=> attempt rescaling of poorly scaled problems

NEWS.md, Project.toml, src/serialization.jl
The loosening of the type restriction on the filename-based methods for `saveoptsum` and `restoreoptsum!` means that users can pass anytype for which `open` is defined, e.g. `<:AbstractPath`. 
=> loosen type restriction on filename for optsum serialization and rename arg

NEWS.md, Project.toml, src/linearmixedmodel.jl, test/pls.jl
- Modify the `obj` function in `fit!` for a `LinearMixedModel` to return the previously calculated `optsum.finitial` when `isone(iter += 1)`
Did behavior change? Did you add new features? If so, please update NEWS.md
=> Avoid repeating first objective evaluation in fit!

src/MixedModels.jl, src/linalg/cholUnblocked.jl, src/linalg/logdet.jl, src/linalg/rankUpdate.jl, test/linalg.jl
- Add checks of `require_one_based_indexing` and macro calls `@inbounds` in some files in the `linalg` directory
- Add more checks for positive definiteness in `cholUnblocked.jl`.
- Although this commit allows for `rankUpdate!` of the upper triangle it turns out that this is much slower than updating the lower triangle.
```julia
julia> using BenchmarkTools, LinearAlgebra, MixedModels
[ Info: Precompiling MixedModels [ff71e718-51f3-5ec2-a782-8ffcbfa3c316]
julia> const contrasts = Dict{Symbol,Any}(:subj => Grouping(), :s => Grouping(), :d => Grouping(), :dept => Grouping(), :service => EffectsCoding());
julia> const form = @formula(y ~ 1 + service + (1|s) + (1|d) + (1|dept));
julia> insteval = MixedModels.dataset(:insteval);
julia> iem01 = fit(MixedModel, form, insteval; contrasts) …
```
=> Extend rankUpdate! method to allow for upper tri

NEWS.md, Project.toml, src/arraytypes.jl, src/linearmixedmodel.jl, src/precompile_MixedModels.jl, src/remat.jl, test/UniformBlockDiagonal.jl
closes #643 
- Previously the sequence of operations in `updateL!` was to copy blocks of `A` to the corresponding block of `L` then iterate over the random effects terms scaling the diagonal block and inflating the diagonal.
- This PR combines those operations on the diagonal blocks, replacing separate calls to `copyto!` and `scaleinflate!` by `copyscaleinflate!`.
- This reduces the number of times iterating over the diagonal elements, which may help with further enhancements such as using [RectangularFullPacked](https://github.com/JuliaLinearAlgebra/RectangularFullPacked.jl) storage for triangular blocks of `L`.
- Closes #643
=> Combine updateL! operations on diagonal blocks

NEWS.md, Project.toml, src/grouping.jl, test/predict.jl
=> allow predicting from a single observation

issues/638/Manifest.toml, issues/638/Project.toml, issues/638/main.jl, src/linearmixedmodel.jl, src/remat.jl
I made it return the same result as lme4.
=> more tinkering on 638

NEWS.md, docs/make.jl, src/generalizedlinearmixedmodel.jl
Should we release your changes right away? 
> No, should be bundled in #639 
If so, bump the version:
=> don't fit a GLM when fixed effects are empty

NEWS.md, benchmark/benchmarks.jl
- Revise benchmark code for modern Julia
- Change the global `contrasts` to a single `Dict{Symbol,Any}` instead of a `Dict` of `Dict`s.
No need to release these changes right away.
=> Update benchmarks, single global contrasts Dict

NEWS.md, Project.toml, docs/src/bootstrap.md, src/bootstrap.jl, src/utilities.jl, test/bootstrap.jl, test/utilities.jl
=> Deprecate mulithreading in bootstrap

NEWS.md, src/predict.jl, test/predict.jl
=> support rank deficiency in prediction

NEWS.md, Project.toml, src/randomeffectsterm.jl, test/FactorReTerm.jl
=> better compatibility with RegressionFormulae.jl

test/modelcache.jl
Avoid redefinition of a method in an included file (#691)
Julia v1.10.0-DEV warns about this when running tests.
=> avoid repeated def of models method

NEWS.md, Project.toml, src/serialization.jl, test/pls.jl
Turns out that floating point is hard. :)
=> Add tolerances in deserialization

NEWS.md, Project.toml, src/generalizedlinearmixedmodel.jl, src/mixedmodel.jl, test/pirls.jl, test/pls.jl
* More informative error messages when passing a `Distribution` or `Link` type instead of the desired instance.
* More informative error message on the intentional decision not to define methods for the coefficient of determination.
* NB: we still don't export `r2` or `adjr2` but these functions might be scope from some other package. We just define methods for them.
Not sure how I feel about adding in these safety features -- @dmbates please feel free to reject all or part of this.
inspired by #696 and #697
=> More informative error messages

NEWS.md, Project.toml, src/linearmixedmodel.jl, test/pls.jl
=> better error when formula variables missing from dataset

NEWS.md, Project.toml, src/linearmixedmodel.jl, src/remat.jl, test/FactorReTerm.jl
I've used this a few times when working on plotting.
=> Add `coefnames(::ReMat)`

Project.toml, src/bootstrap.jl
=> fix typo that changes scale

NEWS.md, docs/src/bootstrap.md, src/bootstrap.jl, src/utilities.jl, test/bootstrap.jl, test/utilities.jl
=> deprecate `hide_progress`

Project.toml, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl
Fixes: https://github.com/JuliaStats/MixedModels.jl/issues/719 
=> usage of ProgressUnknown fixed

src/remat.jl, test/pls.jl
I don't know what's changed in the nightly but something about catching the exception messes up the `@test_logs` check even though the error is still being logged. This fixes that and simplifies things a bit.
=> nest log and throws tests (1.11-nightly compat)

test/matrixterm.jl
Because the initial values for the theta parameters are derived from the values stored in the reterms they will be the final parameter estimates if those terms are deep copied to create a new model.
The NLopt optimizers don't object to this but the PRIMA optimizers do.
=> A test using a deep copy of a model should reset the initial parameter values.

NEWS.md, Project.toml, src/remat.jl
=> Replace broadcasted lambda with explicit loop

NEWS.md, src/linalg.jl, src/linalg/rankUpdate.jl, src/linearmixedmodel.jl, src/remat.jl, test/pls.jl
=> use FMA where possible in fitting

.github/workflows/nightly.yml, .gitignore, NEWS.md, Project.toml, src/bootstrap.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/simulate.jl, test/bootstrap.jl
=> Support for rank deficiency in bootstrap 

.github/workflows/current.yml
no release necessary
I like the idea of testing another CPU architecture to work as further sanity check on our numerical tolerances.
=> add Apple silicon to CI

docs/src/bootstrap.md
=> use `@everywhere ` in distributed bootstrap example

src/MixedModels.jl
Some of the names listed for explicit imports are no longer needed.  I think this can be regarded as an internal change.
=> Update for ExplicitImports check

NEWS.md, Project.toml, src/generalizedlinearmixedmodel.jl
@dmbates is there a giant footgun I'm missing by swapping to "delegate by default" instead of "delegate by explicit list"? 
=> delegate as many GLMM properties as possible to internal LMM

Project.toml, src/MixedModels.jl
treating this as a patch release -- previously it wasn't explicitly exported, but it was accessible until we moved to using explicit imports of every binding
=> import and re-export `lrtest`

src/linalg/logdet.jl, src/linearmixedmodel.jl
=> Force return type on pwrss and logdet to provide stable type inference on objective

NEWS.md, src/generalizedlinearmixedmodel.jl, src/likelihoodratiotest.jl, src/linalg/logdet.jl, src/linalg/rankUpdate.jl, src/linearmixedmodel.jl, src/mixedmodel.jl, src/predict.jl, src/profile/thetapr.jl, src/randomeffectsterm.jl, src/remat.jl, src/simulate.jl, src/utilities.jl
I think this is a slightly more effective (even more microseconds saved!) way of enhancing the type inference.
=> use ::Matrix{T} instead of ::T to aid type inference

NEWS.md, Project.toml, src/MixedModels.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/optsummary.jl
=> Small performance tweaks

.gitignore, NEWS.md, Project.toml, src/MixedModels.jl, src/serialization.jl, test/pls.jl
=> More sophisticated checks in restoreoptsum.

.github/workflows/minimum.yml, README.md
It's increasingly hard to impossible to get the older macOS 11 Big Sur runners and that OS is no longer supported by Apple.
=> bump minimum tested compat for macOS to Monterey

NEWS.md, Project.toml, src/bootstrap.jl, src/simulate.jl, test/bootstrap.jl
<details><summary> visual example that makes the old behavior clear </summary>
```julia
using DataFrames
using MixedModels
using StableRNGs
using Statistics
using Test
id = lpad.(string.(1:40), 2, "0")
B = ["b0", "b1", "b2"]
C = ["c0", "c1", "c2", "c3", "c4"]
df = DataFrame(reshape(collect(Iterators.product(B, C, id)), :), [:b, :c, :id])
df[!, :y] .= 0
filter!(df) do row
b = last(row.b)
c = last(row.c)
return b != c
end
m = LinearMixedModel(@formula(y ~ 1 + b * c + (1|id)), df)
β = 1:rank(m)
σ = 1
simulate!(StableRNG(628), m; β, σ)
fit!(m)
boot = parametricbootstrap(StableRNG(271828), 1000,  m);
bootci = DataFrame(shortestcovint(boot)) …
```
=> rework passing and handling of FE coefficients to `simulate`! for rank deficient models

NEWS.md, Project.toml, src/bootstrap.jl, src/mixedmodel.jl
=> tolerances for issingular

NEWS.md, Project.toml, src/profile/fixefpr.jl, src/profile/profile.jl, test/pls.jl, test/runtests.jl
=> fix flipped lower and upper in profile CI

NEWS.md, Project.toml, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/optsummary.jl, src/serialization.jl, test/pirls.jl, test/pls.jl
=> restore and save optsum for GLMM

.github/workflows/minimum.yml, NEWS.md, Project.toml, src/profile/profile.jl, test/pls.jl
=> add finally block for restoring original model in profiling

NEWS.md, Project.toml, docs/src/optimization.md, ext/MixedModelsPRIMAExt.jl, src/MixedModels.jl, src/bootstrap.jl, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, src/mimeshow.jl, src/mixedmodel.jl, src/nlopt.jl, src/optsummary.jl, src/prima.jl, src/profile/fixefpr.jl, src/profile/profile.jl, src/profile/sigmapr.jl, src/serialization.jl, test/mime.jl, test/pirls.jl, test/pls.jl, test/prima.jl
closes #619, closes #689, closes #742
=> refactor optimization to make it easy to add new backends

NEWS.md, Project.toml, src/MixedModels.jl, test/misc.jl
this (draft) PR adds `settheta!` and `profilesigma` as aliases for `setθ!` and `profileσ` respectively. This is useful when displaying code in LaTeX. One place where this is really needed is arxiv preprints, as arxiv does not (currently) accept xelatex or lualatex, and making unicode symbols work in pdflatex adds a lot of burden. 
Tagging @dmbates as he might have suggestions/comments.
=> added function aliases that dont contain unicode characters for convenience

NEWS.md, Project.toml, src/MixedModels.jl, src/likelihoodratiotest.jl, test/likelihoodratiotest.jl
=> LikelihoodRatioTest extends StatsAPI.HypothesisTest

docs/src/api.md, docs/src/constructors.md, docs/src/index.md, docs/src/mime.md, docs/src/rankdeficiency.md
- Fixed some typos in the documentation, like repeated words and missing closing parentheses. 
- Put package names inside backquotes in multiple places
Did behavior change? Did you add need features? **No**
=> small fixes in documentation

NEWS.md, Project.toml
Did behavior change? Did you add need features? If so, please update NEWS.md. 
The only change is to allow version 0.19 of BSplineKit which does not generate warnings in julia-v0.12-beta and julia-v0.13-nightly.
=> Allow version 0.19 of BSplineKit - to silence warnings

.github/workflows/minimum.yml, NEWS.md, Project.toml, README.md, src/generalizedlinearmixedmodel.jl, src/linearmixedmodel.jl, test/pirls.jl, test/prima.jl
- closes #826 
- closes #827
I think the error with the `cbpp` tests that @dmbates reported in #827 is due to our tight testing tolerances and the slight change in what `unfit!` does for the internal LMM, which causes ever an ever so slightly different value for the optimum to be found
=> reset optsum.final in unfit!

NEWS.md, src/predict.jl, test/fit.jl, test/predict.jl
=> allow specifying `type` argument  in GLMM predict on original data

NEWS.md, Project.toml, src/grouping.jl, test/grouping.jl
=> fix for Grouping() with latest CategoricalArrays

.github/workflows/current.yml, .github/workflows/documenter.yml, .github/workflows/minimum.yml, .github/workflows/nightly.yml, NEWS.md, Project.toml, src/bootstrap.jl, test/bootstrap.jl
* fix display and confint of bootstrap for models without dispersion parameter
* NEWS
* patch not minor
(cherry picked from commit ec7b98695ce959ef21b980bf4e3042df646a4c9b)
=> fix display and confint of bootstrap for models without dispersion parameter

NEWS.md, Project.toml, src/bootstrap.jl
=> display fix for unlikely but possible type inference failure in bootstrap table
